name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env: 
     AZURE_CREDS: ${{ secrets.AZURE_CREDENTIALS }}
     AZURE_SP_NAME: ${{ secrets.TF_CLIENT_ID }}
     AZURE_SP_PASSWORD: ${{ secrets.TF_CLIENT_SECRET }}
     AZURE_TENANT_ID: ${{ secrets.TF_TENANT_ID }}
     AZURE_SUBSCRIPTION_ID: ${{ secrets.TF_SUBSCRIPTION_ID }}
     AZURE_ENV: ${{ secrets.TF_AZURE_ENVIRONMENT }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: $AZURE_CREDS

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
         - az cloud set --name $AZURE_ENV
         - az login --service-principal -u $AZURE_SP_NAME -p $AZURE_SP_PASSWORD --tenant $AZURE_TENANT_ID
         - az account set --subscription $AZURE_SUBSCRIPTION_ID
         - export ARM_CLIENT_ID=${​AZURE_SP_NAME}​
         - export ARM_CLIENT_SECRET=${​AZURE_SP_PASSWORD}​
         - export ARM_SUBSCRIPTION_ID=$(az account show --query id | xargs)
         - export ARM_TENANT_ID=$(az account show --query tenantId | xargs)
         - export ARTIFACT_STORAGE_ACCOUNT_NAME=vafccarcadie${​ENVIRONMENT_ABBR,,}​artistg01
         - export ARTIFACT_RESOURCE_GROUP_NAME=AZ-VA-FCC-ARCADIE-${​ENVIRONMENT_ABBR^^}​-ART-RGP-01
    
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan

      # On push to master, build or change infrastructure according to Terraform configuration files    
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
